### ISSUE TITLE
Hi, I've a question!

### ISSUE THREAD

**Issue by dannyboy0103** [kewlbear/Open3D#1]
It's amazing what you've done!

I wanna try this all by myself, with newest version of open3d from intel.

Do I need to change some codes from original intel's git? or doesn't need to?

Because I'm quite new in this area, any help might great help for me.

**Comment by kewlbear** [comment]
Sorry for answering so late.  If you are trying from scratch without my patches, you need to change some codes.  When you need some hints check out my commits in this repo.  :)
